function createfigure(YData1, XData1, YData2, X1, Y1)
%CREATEFIGURE(YData1, XData1, YData2, X1, Y1)
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  YDATA2:  patch ydata
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 31-May-2024 00:31:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create patch
patch('Parent',axes1,'YData',YData1,'XData',XData1,'LineStyle','none',...
    'FaceColor',[0.75 0.75 0.75]);

% Create patch
patch('Parent',axes1,'YData',YData2,'XData',XData1,'LineStyle','none',...
    'FaceColor',[0.5 0.5 0.5]);

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0 0 0]);

box(axes1,'on');
hold(axes1,'off');
